local header = {
  -- "                                       ",
  -- " -/- /_   _   __/   _  __,   ,__,      ",
  -- "_/__/ (__(/__(_/(__(/_(_/(__/ / (__(_/_",
  -- "                                   _/_ ",
  -- "                                  (/   ",
  -- "                                       ",

  [[                               ]],
  [[    /)        /)               ]],
  [[_/_(/    _  _(/  _  _  __      ]],
  [[(__/ )__(/_(_(__(/_(_(_/ (_(_/_]],
  [[                          .-/  ]],
  [[                         (_/   ]],
  [[                               ]],

  -- [[     I8    ,dPYb,                      8I                                             ]],
  -- [[   I8    IP'`Yb                      8I                                               ]],
  -- [[88888888 I8  8I                      8I                                               ]],
  -- [[   I8    I8  8'                      8I                                               ]],
  -- [[   I8    I8 dPgg,    ,ggg,     ,gggg,8I   ,ggg,     ,gggg,gg   ,ggg,,ggg,   gg     gg ]],
  -- [[   I8    I8dP" "8I  i8" "8i   dP"  "Y8I  i8" "8i   dP"  "Y8I  ,8" "8P" "8,  I8     8I ]],
  -- [[  ,I8,   I8P    I8  I8, ,8I  i8'    ,8I  I8, ,8I  i8'    ,8I  I8   8I   8I  I8,   ,8I ]],
  -- [[ ,d88b, ,d8     I8, `YbadP' ,d8,   ,d8b, `YbadP' ,d8,   ,d8b,,dP   8I   Yb,,d8b, ,d8I ]],
  -- [[88P""Y8888P     `Y8888P"Y888P"Y8888P"`Y8888P"Y888P"Y8888P"`Y88P'   8I   `Y8P""Y88P"888]],
  -- [[                                                                                 ,d8I']],
  -- [[                                                                               ,dP'8I ]],
  -- [[                                                                              ,8"  8I ]],
  -- [[                                                                              I8   8I ]],
  -- [[                                                                              `8, ,8I ]],
  -- [[                                                                               `Y8P"  ]],
}

local color_map = {
  {
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      0,
      1,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      1,
      2,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      2,
      3,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      3,
      4,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      4,
      5,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      5,
      6,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      6,
      7,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      7,
      8,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      8,
      9,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      9,
      10,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      10,
      11,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      11,
      12,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      12,
      13,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      13,
      14,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      14,
      15,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      15,
      16,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      16,
      17,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      17,
      18,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      18,
      19,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      19,
      20,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      20,
      21,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      21,
      22,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      22,
      23,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      23,
      24,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      24,
      25,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      25,
      26,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      26,
      27,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      27,
      28,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      28,
      29,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      29,
      30,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      30,
      31,
    },
  },
  {
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      0,
      1,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      1,
      2,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      2,
      3,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      3,
      4,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay3',
      4,
      5,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay3',
      5,
      6,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      6,
      7,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      7,
      8,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      8,
      9,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      9,
      10,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      10,
      11,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      11,
      12,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      12,
      13,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      13,
      14,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay8',
      14,
      15,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay8',
      15,
      16,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      16,
      17,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      17,
      18,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      18,
      19,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      19,
      20,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      20,
      21,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      21,
      22,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      22,
      23,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      23,
      24,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      24,
      25,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      25,
      26,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      26,
      27,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      27,
      28,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      28,
      29,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      29,
      30,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      30,
      31,
    },
  },
  {
    {
      'AlphaJemuelKwelKwelWalangTatay1',
      0,
      1,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay1',
      1,
      2,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay2',
      2,
      3,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay2',
      3,
      4,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay3',
      4,
      5,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      5,
      6,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      6,
      7,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      7,
      8,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      8,
      9,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay5',
      9,
      10,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      10,
      11,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      11,
      12,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay7',
      12,
      13,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay7',
      13,
      14,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay8',
      14,
      15,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      15,
      16,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      16,
      17,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay9',
      17,
      18,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      18,
      19,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      19,
      20,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayB',
      20,
      21,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      21,
      22,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      22,
      23,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayC',
      23,
      24,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayD',
      24,
      25,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      25,
      26,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      26,
      27,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      27,
      28,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      28,
      29,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      29,
      30,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      30,
      31,
    },
  },
  {
    {
      'AlphaJemuelKwelKwelWalangTatay1',
      0,
      1,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay1',
      1,
      2,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay2',
      2,
      3,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay2',
      3,
      4,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      4,
      5,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay3',
      5,
      6,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay4',
      6,
      7,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay4',
      7,
      8,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay5',
      8,
      9,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay5',
      9,
      10,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay6',
      10,
      11,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay6',
      11,
      12,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay7',
      12,
      13,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay7',
      13,
      14,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay8',
      14,
      15,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay8',
      15,
      16,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay9',
      16,
      17,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay9',
      17,
      18,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayA',
      18,
      19,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayA',
      19,
      20,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayB',
      20,
      21,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayB',
      21,
      22,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayC',
      22,
      23,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayC',
      23,
      24,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      24,
      25,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayD',
      25,
      26,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayE',
      26,
      27,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayE',
      27,
      28,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayF',
      28,
      29,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayF',
      29,
      30,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayF',
      30,
      31,
    },
  },
  {
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      0,
      1,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      1,
      2,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      2,
      3,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      3,
      4,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      4,
      5,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      5,
      6,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      6,
      7,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      7,
      8,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      8,
      9,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      9,
      10,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      10,
      11,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      11,
      12,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      12,
      13,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      13,
      14,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      14,
      15,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      15,
      16,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      16,
      17,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      17,
      18,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      18,
      19,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      19,
      20,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      20,
      21,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      21,
      22,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      22,
      23,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      23,
      24,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      24,
      25,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      25,
      26,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayE',
      26,
      27,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayE',
      27,
      28,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayF',
      28,
      29,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      29,
      30,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      30,
      31,
    },
  },
  {
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      0,
      1,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      1,
      2,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      2,
      3,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      3,
      4,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      4,
      5,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      5,
      6,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      6,
      7,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      7,
      8,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      8,
      9,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      9,
      10,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      10,
      11,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      11,
      12,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      12,
      13,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      13,
      14,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      14,
      15,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      15,
      16,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      16,
      17,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      17,
      18,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      18,
      19,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      19,
      20,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      20,
      21,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      21,
      22,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      22,
      23,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      23,
      24,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      24,
      25,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayD',
      25,
      26,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayE',
      26,
      27,
    },
    {
      'AlphaJemuelKwelKwelWalangTatayE',
      27,
      28,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      28,
      29,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      29,
      30,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      30,
      31,
    },
  },
  {
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      0,
      1,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      1,
      2,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      2,
      3,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      3,
      4,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      4,
      5,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      5,
      6,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      6,
      7,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      7,
      8,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      8,
      9,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      9,
      10,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      10,
      11,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      11,
      12,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      12,
      13,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      13,
      14,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      14,
      15,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      15,
      16,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      16,
      17,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      17,
      18,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      18,
      19,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      19,
      20,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      20,
      21,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      21,
      22,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      22,
      23,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      23,
      24,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      24,
      25,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      25,
      26,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      26,
      27,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      27,
      28,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      28,
      29,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      29,
      30,
    },
    {
      'AlphaJemuelKwelKwelWalangTatay0',
      30,
      31,
    },
  },
}

local my_ayu_colors = {
  ['0'] = { fg = '#000000', force = true },
  ['1'] = { fg = '#ff6fd3', force = true },
  ['2'] = { fg = '#ff6dc9', force = true },
  ['3'] = { fg = '#ff6bbf', force = true },
  ['4'] = { fg = '#ff6ab5', force = true },
  ['5'] = { fg = '#ff6cab', force = true },
  ['6'] = { fg = '#ff6ea2', force = true },
  ['7'] = { fg = '#ff7099', force = true },
  ['8'] = { fg = '#ff718f', force = true },
  ['9'] = { fg = '#ff7286', force = true },
  ['A'] = { fg = '#ff727c', force = true },
  ['B'] = { fg = '#ff7673', force = true },
  ['C'] = { fg = '#ff796b', force = true },
  ['D'] = { fg = '#ff7d63', force = true },
  ['E'] = { fg = '#fc815c', force = true },
  ['F'] = { fg = '#f78555', force = true },
}

local set_hl_groups = function()
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatay0', { fg = '#000000' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatay1', { fg = '#ff6fd3' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatay2', { fg = '#ff6dc9' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatay3', { fg = '#ff6bbf' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatay4', { fg = '#ff6ab5' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatay5', { fg = '#ff6cab' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatay6', { fg = '#ff6ea2' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatay7', { fg = '#ff7099' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatay8', { fg = '#ff718f' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatay9', { fg = '#ff7286' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatayA', { fg = '#ff727c' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatayB', { fg = '#ff7673' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatayC', { fg = '#ff796b' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatayD', { fg = '#ff7d63' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatayE', { fg = '#fc815c' })
  vim.api.nvim_set_hl(0, 'AlphaJemuelKwelKwelWalangTatayF', { fg = '#f78555' })
end

-- vim.api.nvim_create_autocmd('ColorScheme', {
--   pattern = '*',
--   callback = function()
--     -- print 'Hit callback'
--     -- print(debug.getinfo(2).name)
--     local dashboard = require 'alpha.themes.startify'
--     -- colorize(header, color_map, colors)
--     -- print "setting colors in ayu..."
--     -- print(dashboard.section.header.opts.hl)
--     set_hl_groups()
--     dashboard.section.header.val = header
--     -- dashboard.section.header.opts.hl = colorize(header, color_map, my_ayu_colors)
--     dashboard.section.header.opts.hl = color_map
--     -- print 'set colors in ayu'
--     -- print(dashboard.section.header.opts.hl)
--   end,
--   group = vim.api.nvim_create_augroup('FixAlphaHeader', { clear = true }),
-- })

-- tableIO.save(colorize(header, color_map, my_ayu_colors), "COLORTABLE.lua")

return {
  'Shatur/neovim-ayu',
  name = 'ayu',
  config = function()
    -- require("ayu").setup {
    --   mirage = true,
    --   terminal = false,
    -- }
    local ayu = require 'ayu'

    local colors = require 'ayu.colors'
    colors.generate(true)

    ayu.setup {
      mirage = true,
      -- terminal = true,
      overrides = function()
        if vim.o.background == 'dark' then
          return {}
        else
          return {
            LineNr = { fg = colors.accent },
            CursorLineNr = { fg = colors.bg, bg = colors.accent },
            LspCodeLens = { fg = '#bbbbbb', bg = '#efefef' },
          }
        end
      end,
    }
    ayu.colorscheme()
  end,
}
